### ISSUE TITLE
The program is already running. Please do not start i....

### ISSUE THREAD

**Issue by gulubao** [ccslykx/Starry#5]
OS: Ubuntu 22.04
XDG_CURRENT_DESKTOP: ubuntu:GNOME; GNOME Shell 42.9
Pot: 2.6.6, deb安装

问题:
    在starry“执行脚本”处填pot popclip $PLAINTEXT. 
    划词点击pot后出现弹窗"The program is already running. Please do not start i....".
    无翻译界面. 

补充信息:
    在命令行直接输入pot也会出现弹窗"The program is already running. Please do not start i....".

**Comment by gulubao** [comment]
将执行脚本修改为 https://github.com/pot-app/pot-desktop 中的 curl "127.0.0.1:60828/selection_translate" 可以正常工作.

**Comment by joezhouchenye** [comment]
最新版本，上面的不行。

curl  -X POST -d $PLAINTEXT http://127.0.0.1:60828/

这样可以，配合Pot设置中需要打开窗口默认置顶

不过一开始是因为Pot里面快捷键时灵时不灵才来看看这个Starry，但发现窗口默认置顶打开后快捷键也没问题了。。。

这个Starry可以弃了
